### ISSUE TITLE
miio discover errors using a virgin device

### ISSUE THREAD

**Issue by marco79cgn** [aholstenson/miio#109]
Hi,
 I just received a brand new Mi Robot V1 which has never been paired with a WiFi or the App.
 
 I installed the latest miio (0.15.5) and tried a miio discover. It took me about 3 tries and I had to wait for at least 6 minutes to get the following result. Obviously, the json can't be parsed. Can I be sure that this token is correct? (I masked it with ff)

``` 
thing:miio:74399767 <- Handshake reply: <Buffer 58 37 48 4a 55 ff ff ff ff ff ff ff 55 70 42 65> +0ms
  thing:miio:74399767 Using automatic token: 5837484a55ffffffffffffff55704265 +7ms
  thing:miio:74399767 -> (5) {"method":"miIO.info","params":[],"id":1} +2ms
  thing:miio:74399767 <- Message: `` +47ms
  thing:miio:74399767 <- Invalid JSON SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/miio/lib/safeishJSON.js:10:15)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/miio/lib/network.js:367:18)
    at Socket._socket.on (/usr/local/lib/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:160:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) +1ms
  thing:miio:74399767 -> (4) {"method":"miIO.info","params":[],"id":101} +2s
  thing:miio:74399767 <- Message: `` +11ms
  thing:miio:74399767 <- Invalid JSON SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/miio/lib/safeishJSON.js:10:15)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/miio/lib/network.js:367:18)
    at Socket._socket.on (/usr/local/lib/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:160:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) +1ms
  thing:miio:74399767 -> (3) {"method":"miIO.info","params":[],"id":201} +2s
  thing:miio:74399767 -> (2) {"method":"miIO.info","params":[],"id":301} +2s
  thing:miio:74399767 -> (1) {"method":"miIO.info","params":[],"id":401} +2s
  thing:miio:74399767 -> (0) {"method":"miIO.info","params":[],"id":501} +2s
  thing:miio:74399767 Using automatic token: 5837484a55ffffffffffffff55704265 +7s

**Comment by aholstenson** [comment]
Thanks for opening an issue! The token is correct as the vacuum is responding to the `miIO.info`-requests even though the reply is garbage.

The vacuums are a bit tricky in general, and as far as I'm aware have an issue where they can't be controlled over the local network unless they are also connected to the Xiaomi servers.

There seems to be a way to use [dustcloud](https://github.com/dgiese/dustcloud) to enable local control, but that involves rooting the device, probably voiding any warranty and risk breaking your device.

So if you really do not want to connect to Xiaomis servers you can try that, otherwise set it up in the app and then extract the token. The token probably needs to be extracted from the app itself, this repo has no documentation (#93) but a good guide is available here: https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token_mirobot_new.md

**Comment by marco79cgn** [comment]
Thanks for your help. I finally managed to get a valid token but this is impossible with miio, neither the latest version (0.15.5) nor an older version (0.14.x) returned a token which was valid at the end. The latest version won't return anything if not running it in debug mode. The older version returned this (which also didn't work eventually after pairing it with the app):
```Device ID: 743*****
Model info: Unknown 
Address: 192.168.8.1 
Token: 424d44434b34364f756f5141744f754f via auto-token
Support: Unknown

I had to set it up in the app and extract it from a local unencrypted backup. Even here, the iOS part of your linked documentation is already outdated, as the token is stored in hex with 96 digits (AES). You have to decrypt it back to 32 digits, e.g. with the help of an online tool like this: http://aes.online-domain-tools.com

Another problem I stumbled on was that common homebridge plugins (like homebridge-xiaomi-mi-robot-vacuum) don't work together with the latest miio version. I had to explicitly downgrade miio to 0.14.1 in order to get them to work using `sudo npm install -g miio@0.14.1`.

**Comment by aholstenson** [comment]
Good to hear that you managed to get it to work! The behavior of the vacuum is why the docs need to be updated, there has been changes made where it regenerates its token when it is connected to the cloud. Which is why docs is needed for how to extract tokens from the Mi Home apps for both Android and iOS. If you are interested in the progress, follow #93 as it will updated when I get around to it.

The homebridge plugins are an issue as many of them depend on `miio` globally which is not recommended. If you have the time please open issues in the repos of the plugins you have tried to encourage the authors to properly include `miio` as a dependency in their projects.
