### ISSUE TITLE
how to pack a new message

### ISSUE THREAD

**Issue by brianping7** [aholstenson/miio#34]
I just say the latest gateway API supports event simulation, like you could simulate the double click switch action. 

i couldn't find where to pack the new message to the device, would mind explain little bit, how to implement a new function to simulate the sub device event? many thanks.

**Comment by aholstenson** [comment]
I'm not familiar with this feature of the gateway, do you have a link to the documentation for it? 

For normal interaction with a device they emit events, most things on the gateway are exposed as controllers and are documented at https://github.com/aholstenson/miio/blob/master/docs/devices/controller.md

**Comment by brianping7** [comment]
https://cdn.cnbj2.fds.api.mi-img.com/lumiaiot/common/gateway/%E7%BB%BF%E7%B1%B3%E7%BD%91%E5%85%B3%E5%B1%80%E5%9F%9F%E7%BD%91%E9%80%9A%E4%BF%A1%E5%8D%8F%E8%AE%AEV1.0.7_2017.05.25_01.doc

this is a chinese doc, it mentioned, we could send write cmd to gateway as follow.
{"cmd":"write","model":"switch","sid":"112316","short_id":4343,"data":"{\"status\":\"click\"}" }
this could simulate the click event.

**Comment by brianping7** [comment]
can you explain me a liitle bit where you process the heartbeat message from gateway. i can't ready any heartbeat message. thanks.

**Comment by aholstenson** [comment]
The library has all the code related to the Local Developer API in the file `lib/devices/gateway.js`, but it's not used much. Instead of using the developer API for calls (writes in the documentation) I've opted to use it only for reports (such as clicks on a switch or temperature changes) to stay compatible with other libraries that use the Developer API.

If you want to send write commands via the Developer API to your gateway you should look into other libraries for the Aqara gateway, there are several libraries if you search through NPM that should be able to do what you are looking for.
