### ISSUE TITLE
Xiaomi Mi Smart Socket - Can't change state

### ISSUE THREAD

**Issue by camfrout** [aholstenson/miio#52]
Hi,

I am trying to control my Xiamo Mi Smart Socket but I can't seem to be able to turn the plug on or off.

Output of miio --inspect 192.168.xx.xxx
```
 INFO  Attempting to inspect 192.168.xx.xxx

Device ID: 45286364
Model info: chuangmi.plug.m1 (power-plug)
Address: 192.168.xx.xxx (chuangmi-plug-m1_miio4528xxxx)
Token: 0480404f6870c4d2e0ea19271d1e4261 via auto-token
Support: At least basic

Firmware version: 1.2.4_17
Hardware version: MW300

WiFi: xxxxx (00:60:64:E1:xx:xx) RSSI: -58
WiFi firmware version: SD878x-14.76.36.p84-702.1.0-WM

Remote access (Mi Home App): TCP

Properties:
  - powerChannel0: false
  - power: { '0': false }
```

But when I execute the following script, it runs forever without returinng any error:
```
const miio = require('miio');

// Create a new device over the given address
miio.device({
	address: '192.168.xx.xxx' , token: '0480404f6870c4d2e0ea19271d1e4261'
}).then(device => {
	if(device.hasCapability('power')) {
		console.log('power is now', device.power);
		return device.setPower(! device.power);
	}
}).catch(console.error);
```

I have discovered the token by re-initiating my plug and running  `miio --discover` while I was connecting to the plug wifi. I then finished to set up the plug through my iPhone.

**Comment by aholstenson** [comment]
Thank you for your issue report.

Smart sockets do not have the `power` capability, but instead have the `power-channels` capability. You can see the methods they support in the documentation for [power plugs](https://github.com/aholstenson/miio/blob/master/docs/devices/power-plug.md).

If want to keep using `hasCapability` you should check for `power-channels` instead of `power` in the example you gave.
