### ISSUE TITLE
cli control delay

### ISSUE THREAD

**Issue by nutinshell** [aholstenson/miio#64]
When issue ```miio --control ip --token token --method get_prop``` command, it always takes 3-5s to complete, is there any way to make it quickly response? Thanks.

**Comment by aholstenson** [comment]
The `miio` command isn't really intended to be used for controlling devices in that way. It's mainly for managing tokens and figuring out the API of devices.

Pull requests are welcome for better control-functionality with faster connections and use of the actual device API instead of the raw protocol commands.

I'll close this issue, but feel free to open another one if you have any other questions.
