### ISSUE TITLE
Vacuum Robot --> Hint!

### ISSUE THREAD

**Issue by realhoffi** [aholstenson/miio#86]
Hi,
the following project has a working vacuum feature! Maybe you can talk to the author to copy the code?

https://github.com/ioBroker/ioBroker.mihome-vacuum

greetings 👍

**Comment by aholstenson** [comment]
Thanks for opening an issue. Are there any features available in the linked implementation that miio does not currently support?

**Comment by jghaanstra** [comment]
I think @realhoffi is referring to the fact that miio does not work at all for a lot of Mi Robot Vacuum Cleaner owners. It worked good for everybody on previous firmware versions of the robot but since the latest two firmware updates of the robot, miio is timing out in it's communication and not a single command gets through. This does not seem to be an issue for everybody but a lot of users seem to be affected by it. Not sure if the ioBroker implementation fixes this though.

Something else to note which could help determine the cause of the timeouts. There is a way to gain root access to the robot: https://github.com/dgiese/dustcloud

**Comment by kokarn** [comment]
Just wanted to say that it's 100% broken for me. Just to give my +1

**Comment by realhoffi** [comment]
well, i think, that the socket opening for the vacuum is different than for the other items! linke @jghaanstra  said a lot of ppl got problems with timing out, Sometimes it is working, sometimes it does not :(

**Comment by circuuz** [comment]
I guess @realhoffi is having the same problem I have. I have tested Miio using the CLI commands and I'm able to discover the vacuum but cannot connect to it whatsoever.
For comparison I also tested this implementation https://github.com/rytilahti/python-miio and it works perfectly.

So I guess something is wrong here. 
Unfortunately my Python skills isn't good enough for me to fully understand the python library to make a PR on my own but I would gladly help with debugging etc.

**Comment by aholstenson** [comment]
The `miio` command in version 0.14 and older was never intended to be used for something like controlling a device so it did a lot of weird stuff when connecting to a device. Networking has been improved in miio 0.15.0 together with direct connecting to devices when IPs are used with the `miio` command.

Issues with tokens and the vacuum, please refer to #93 and the issues linked from there. If you have something to add please add comments! The same goes for #92 if the issue is with discovering that the vacuum exists on the network.

For my own vacuum I'm able to connect to it via `miio.device()` in 0.15.1 and issue commands without any issues. The same goes for the new `miio` command such as via `miio control ipHere clean`.

If any of you are still experiencing issues with connecting to the device when running 0.15.1 or later please open a new issue and we can see if we can figure out why :)
